package org.frc.level02;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class Solution02Test {
    
    // YOU DO NOT EDIT THIS FILE
    //
    // This file verifies that your Solution02 methods follow the rules
    // described in their JavaDocs.
    //
    // Think of each test as a referee checking a rule:
    //   - if the rule is followed → test passes
    //   - if the rule is broken → test fails
    
    /**
     * Verifies that drainBatterySubtract correctly subtracts a fixed amount.
     */
    @Test
    void drainBatterySubtract_basicDrain() {
        
        double actual = Solution02.drainBatterySubtract(100.0, 12.5);
        
        double expected = 87.5;
        
        assertEquals(expected, actual, 0.0001,
                "Expected battery to be 87.5 after subtract drain");
    }
    
    /**
     * Verifies that drainBatterySubtract clamps battery at 0
     * instead of allowing negative values.
     */
    @Test
    void drainBatterySubtract_clampsAtZero() {
        
        double actual = Solution02.drainBatterySubtract(5.0, 10.0);
        
        double expected = 0.0;
        
        assertEquals(expected, actual, 0.0001,
                "Battery should clamp at 0 when over-drained");
    }
    
    /**
     * Verifies that drainBatteryMultiply correctly applies a multiplier.
     */
    @Test
    void drainBatteryMultiply_basicMultiplier() {
        
        double actual = Solution02.drainBatteryMultiply(80.0, 0.9);
        
        double expected = 72.0;
        
        assertEquals(expected, actual, 0.0001,
                "Expected 80 * 0.9 = 72");
    }
    
    /**
     * Verifies that multiplying zero battery always returns zero.
     */
    @Test
    void drainBatteryMultiply_zeroStaysZero() {
        
        double actual = Solution02.drainBatteryMultiply(0.0, 0.9);
        
        double expected = 0.0;
        
        assertEquals(expected, actual, 0.0001,
                "0 multiplied should remain 0");
    }
}
